; AgentForge Windows Installer
; Compiles to AgentForge-Setup.exe via: makensis agentforge.nsi
;
; User experience: double-click .exe -> Welcome -> License Key -> Claude Sign-in -> Install -> Finish
; Handles WSL2, Ubuntu, Node.js, Claude Code, and AgentForge license activation.
;
; Gated model: the clone below is only the public bootstrap CLI. Your tier's content
; (skills/agents/rules/templates) is downloaded by `ecc activate <key>` after the
; license validates server-side. No license key -> a working CLI, no content yet.

!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "WinMessages.nsh"
!include "FileFunc.nsh"

; ---------------------------------------------------------------
; Metadata
; ---------------------------------------------------------------
Name "AgentForge"
OutFile "AgentForge-Setup.exe"
InstallDir "$APPDATA\AgentForge"
RequestExecutionLevel admin
BrandingText "AgentForge -- Your AI team. Ready in 60 seconds."
Unicode True

VIProductVersion "2.1.0.0"
VIAddVersionKey "ProductName" "AgentForge"
VIAddVersionKey "CompanyName" "AgentForge"
VIAddVersionKey "FileDescription" "AgentForge Installer"
VIAddVersionKey "FileVersion" "2.1.0"
VIAddVersionKey "LegalCopyright" "AgentForge 2026"

; Build marker -- printed first in the install log so a support log proves which build ran.
!define BUILD_ID "b20-bugfix3-20260608"

; Verification switch: `makensis -DNOCOMPRESS` leaves the WSL bash commands
; uncompressed in the .exe so `strings -el` can confirm the NSIS->wsl transport did
; not corrupt them (compound bash does not survive that transport -- keep each
; `bash -c` to simple &&/||/;/test/redirects). Normal builds stay compressed.
!ifdef NOCOMPRESS
  SetCompress off
!endif

; ListView messages for the install-log dump (Unicode control -> use the W variant).
; Guard against redefinition -- some NSIS headers already define these.
!ifndef LVM_GETITEMCOUNT
  !define LVM_GETITEMCOUNT 0x1004
!endif
!ifndef LVM_GETITEMTEXTW
  !define LVM_GETITEMTEXTW 0x1073
!endif

; ---------------------------------------------------------------
; Variables
; ---------------------------------------------------------------
Var ApiKeyText
Var ApiKeyHwnd
Var LicenseKey
Var LicenseHwnd
Var SkipActivate
Var NeedsReboot
Var SkipWSLSetup
Var StepNum
Var WslOutput
Var ExitCode
Var LogStamp        ; timestamp shared by the Desktop bundle + the WSL ecc log
Var LogBundle       ; full path to the Desktop log bundle
Var FailHandled     ; "1" once a failure dialog + log dump has been shown
Var Tier            ; friendly activated tier ("Starter"/"Builder"/"Pro"); set post-activation
Var ApiRadioSub     ; HWND of the "use my Claude subscription" radio
Var ApiRadioKey     ; HWND of the "use an Anthropic API key" radio

; ---------------------------------------------------------------
; MUI Settings
; ---------------------------------------------------------------
; Branding assets generated by assets/gen_assets.py (reproduces the storefront
; anvil mark in the brand palette). ${__FILEDIR__} keeps paths valid no matter
; what directory makensis is invoked from; forward slashes for the Linux build box.
!define MUI_ICON   "${__FILEDIR__}/assets/AgentForge.ico"
!define MUI_UNICON "${__FILEDIR__}/assets/AgentForge.ico"
!define MUI_ABORTWARNING

; Inner-page header logo (top-right on every wizard page)
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_RIGHT
!define MUI_HEADERIMAGE_BITMAP "${__FILEDIR__}/assets/header.bmp"
!define MUI_HEADERIMAGE_BITMAP_NOSTRETCH

; Welcome + Finish side panel (164x314, dark-luxury brand art)
!define MUI_WELCOMEFINISHPAGE_BITMAP "${__FILEDIR__}/assets/welcome.bmp"

!define MUI_WELCOMEPAGE_TITLE "Welcome to AgentForge"
!define MUI_WELCOMEPAGE_TEXT "AgentForge sets up a complete Claude Code environment and downloads the AI team for your license tier -- skills, agents, and rules -- ready to use in minutes.$\r$\n$\r$\nThis installer will set up everything you need:$\r$\n$\r$\n  * Windows Subsystem for Linux (WSL2)$\r$\n  * Ubuntu 22.04$\r$\n  * Node.js and developer tools$\r$\n  * Claude Code (AI assistant)$\r$\n  * Your AgentForge tier (Starter, Builder, or Pro)$\r$\n$\r$\nHave your license key ready. Click Next to continue."
; The body text is a placeholder -- FinishpageShow replaces it at runtime with the
; actual activated tier (Starter / Builder / Pro), kept short so it never collides
; with the run checkbox below it.
!define MUI_FINISHPAGE_TITLE "AgentForge is ready"
!define MUI_FINISHPAGE_TEXT "Your AgentForge environment is installed."
!define MUI_FINISHPAGE_NOAUTOCLOSE
; Primary action: open the Command Deck (the premium 3-pane app) via the path-aware
; launcher ~/.agentforge-cockpit (written in step 9b). It runs `ecc cockpit`, which
; starts the local backend (127.0.0.1:7842, detached) and opens the browser. On the
; subscription path the launcher first `unset ANTHROPIC_API_KEY` so no key -- including
; one re-injected by Windows->WSL WSLENV propagation -- shadows the subscription sign-in
; for `claude` run inside the Deck's terminal pane; the API-key launcher omits the unset.
; -lic = login+interactive so .bashrc (PATH / nvm) is sourced before ecc runs.
!define MUI_FINISHPAGE_RUN "$SYSDIR\cmd.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Open the Command Deck now"
!define MUI_FINISHPAGE_RUN_PARAMETERS "/c start wsl.exe -d Ubuntu-22.04 --cd ~ -- bash -lic ~/.agentforge-cockpit"
; Secondary: a quiet link to the support-log folder on the Desktop.
!define MUI_FINISHPAGE_LINK "Open the folder with my setup log"
!define MUI_FINISHPAGE_LINK_LOCATION "$DESKTOP"

; ---------------------------------------------------------------
; Pages
;   Welcome -> License Key -> Claude Sign-in -> Install -> Finish
;   License + Claude auth are both collected BEFORE install: activation needs the
;   key, and capturing the auth choice up front keeps the flow linear and premium.
; ---------------------------------------------------------------
!insertmacro MUI_PAGE_WELCOME
Page custom LicensePageCreate LicensePageLeave
Page custom ClaudeAuthPageCreate ClaudeAuthPageLeave
!insertmacro MUI_PAGE_INSTFILES
!define MUI_PAGE_CUSTOMFUNCTION_SHOW FinishpageShow
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

; ---------------------------------------------------------------
; Macros
; ---------------------------------------------------------------
!macro StepMsg msg
    IntOp $StepNum $StepNum + 1
    DetailPrint "[$StepNum/12] ${msg}"
!macroend

; NOTE: the wsl command is wrapped in a BACKTICK-delimited NSIS string so that the
; bash command (${cmd}) may freely contain single AND double quotes. A single-quoted
; wrapper here truncates any command containing a single quote (it terminates the NSIS
; string early), which silently corrupts e.g. `echo 'x' > file` -> bash sees an unmatched
; quote. Backticks avoid that. Do not pass a backtick inside ${cmd}.
!macro WslExec user cmd
    ${If} "${user}" == "root"
        nsExec::ExecToLog `wsl.exe -d Ubuntu-22.04 -u root -- bash -c "${cmd}"`
    ${Else}
        nsExec::ExecToLog `wsl.exe -d Ubuntu-22.04 -u agentforge -- bash -c "${cmd}"`
    ${EndIf}
    Pop $ExitCode
!macroend

!macro WslCheck cmd
    nsExec::ExecToStack `wsl.exe -d Ubuntu-22.04 -u agentforge -- bash -c "${cmd}"`
    Pop $ExitCode
    Pop $WslOutput
!macroend

; Build the Desktop log bundle, show a friendly dialog pointing at it, then abort.
; Used for every hard failure so a test machine can hand back ONE file.
!macro FailWithLog failmsg
    Call BuildLogBundle
    StrCpy $FailHandled "1"
    MessageBox MB_OK|MB_ICONSTOP "${failmsg}$\r$\n$\r$\nA setup log was saved to:$\r$\n$LogBundle$\r$\n$\r$\nSend us that file and we'll help. You can also retry by running this installer again."
    Abort
!macroend

!macro WslMustPass user cmd failmsg
    !insertmacro WslExec "${user}" "${cmd}"
    ${If} $ExitCode != 0
        !insertmacro FailWithLog "${failmsg}"
    ${EndIf}
!macroend

; ---------------------------------------------------------------
; Init
; ---------------------------------------------------------------
Function .onInit
    StrCpy $NeedsReboot "false"
    StrCpy $SkipWSLSetup "false"
    StrCpy $SkipActivate "false"
    StrCpy $FailHandled "0"
    StrCpy $StepNum 0
    StrCpy $Tier ""

    ; Timestamp used for both the Desktop bundle and the WSL-side ecc log.
    ${GetTime} "" "L" $1 $2 $3 $4 $5 $6 $7
    StrCpy $LogStamp "$3$2$1-$5$6$7"
    StrCpy $LogBundle "$DESKTOP\AgentForge-install-log-$LogStamp.txt"

    IfFileExists "$APPDATA\AgentForge\agentforge-resume.flag" 0 no_resume
        StrCpy $SkipWSLSetup "true"
        Delete "$APPDATA\AgentForge\agentforge-resume.flag"
        DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "AgentForgeResume"
    no_resume:

    ReadRegStr $0 HKLM "SOFTWARE\Microsoft\Windows NT\CurrentVersion" "CurrentBuild"
    ${If} $0 < 19041
        MessageBox MB_OK|MB_ICONSTOP "AgentForge requires Windows 10 version 2004+ (build 19041+).$\r$\n$\r$\nYour build: $0$\r$\nPlease update Windows first."
        Abort
    ${EndIf}

    ; Existing-install detection (skipped during a reboot-resume, where
    ; $SkipWSLSetup is "true"). Installs are idempotent, so this confirms a
    ; reinstall rather than forcing an uninstall-first.
    ${If} $SkipWSLSetup == "false"
        ReadRegStr $0 HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge" "DisplayVersion"
        ${If} $0 != ""
            MessageBox MB_YESNO|MB_ICONQUESTION "AgentForge $0 is already installed on this PC.$\r$\n$\r$\nReinstall now? Your tier content is kept -- to refresh skills and agents later, run in Ubuntu:$\r$\n  ecc update$\r$\n$\r$\nChoose No to cancel. To remove AgentForge, use Windows 'Add or Remove Programs'." IDYES af_reinstall_ok
            Abort
            af_reinstall_ok:
        ${EndIf}
    ${EndIf}
FunctionEnd

; Fired when the install section aborts. Safety net: if a specific failure path
; already built the log + dialog (FailWithLog) or this was an intentional reboot
; exit, stay quiet; otherwise dump the log and point the user at it.
Function .onInstFailed
    ${If} $FailHandled != "1"
        Call BuildLogBundle
        MessageBox MB_OK|MB_ICONSTOP "Setup did not complete.$\r$\n$\r$\nA log was saved to:$\r$\n$LogBundle$\r$\n$\r$\nSend us that file and we'll help."
    ${EndIf}
FunctionEnd

; Finish page SHOW hook: swap the placeholder body for the real activated tier.
; Runs after the text control exists ($mui.FinishPage.Text) and before the page
; paints. Kept to <=3 lines so it never overlaps the run checkbox.
Function FinishpageShow
    ; Skip-activate: no license yet, point them at activation (claude still opens).
    ${If} $SkipActivate == "true"
        StrCpy $0 "Your Claude Code environment is installed.$\r$\n$\r$\nActivate your license in Ubuntu:  ecc activate <your-license-key>"
        SendMessage $mui.FinishPage.Text ${WM_SETTEXT} 0 "STR:$0"
        Return
    ${EndIf}

    ${If} $Tier != ""
        StrCpy $0 "Your $Tier environment is installed"
    ${Else}
        StrCpy $0 "Your AgentForge environment is installed"
    ${EndIf}

    ; Auth-aware tail: empty $ApiKeyText == the subscription path (sign in on first run).
    ${If} $ApiKeyText == ""
        StrCpy $0 "$0.$\r$\n$\r$\nClick Finish -- Claude opens so you can sign in with your Claude subscription."
    ${Else}
        StrCpy $0 "$0 and ready.$\r$\n$\r$\nClick Finish to open Claude."
    ${EndIf}
    SendMessage $mui.FinishPage.Text ${WM_SETTEXT} 0 "STR:$0"
FunctionEnd

; ---------------------------------------------------------------
; Logging: dump the install Details view to one Desktop file
; ---------------------------------------------------------------

; Append the entire install-log ListView to the file whose path is on the stack.
; Standard NSIS technique; Unicode-correct (LVM_GETITEMTEXTW + wide string read).
Function DumpLog
    Exch $5
    Push $0
    Push $1
    Push $2
    Push $3
    Push $4
    Push $6

    FindWindow $0 "#32770" "" $HWNDPARENT
    GetDlgItem $0 $0 1016
    StrCmp $0 0 dl_exit
    FileOpen $5 $5 "a"
    StrCmp $5 "" dl_exit
    SendMessage $0 ${LVM_GETITEMCOUNT} 0 0 $6
    System::StrAlloc ${NSIS_MAX_STRLEN}
    Pop $3
    StrCpy $2 0
    System::Call "*(i, i, i, i, i, i, i, i, i) i (0, 0, 0, 0, 0, r3, ${NSIS_MAX_STRLEN}, 0, 0) .r1"
    dl_loop:
        StrCmp $2 $6 dl_done
        System::Call "User32::SendMessageW(i $0, i ${LVM_GETITEMTEXTW}, i $2, i r1)"
        System::Call "*$3(&t${NSIS_MAX_STRLEN} .r4)"
        FileWrite $5 "$4$\r$\n"
        IntOp $2 $2 + 1
        Goto dl_loop
    dl_done:
        FileClose $5
        System::Free $1
        System::Free $3
    dl_exit:
        Pop $6
        Pop $4
        Pop $3
        Pop $2
        Pop $1
        Pop $0
        Pop $5 ; restore $5 and discard the filename/handle the caller pushed (no stack leak)
FunctionEnd

; Write a system header then the full Details dump to $LogBundle on the Desktop.
; Probes (node/distro/kernel) go through ExecToStack so they never pollute the
; Details view we are about to capture. Safe to call on success or failure.
Function BuildLogBundle
    ClearErrors
    ReadRegStr $R0 HKLM "SOFTWARE\Microsoft\Windows NT\CurrentVersion" "CurrentBuild"

    nsExec::ExecToStack 'wsl.exe -d Ubuntu-22.04 -u agentforge -- bash -c "uname -r 2>/dev/null || echo unknown"'
    Pop $R1
    Pop $R1
    nsExec::ExecToStack 'wsl.exe -d Ubuntu-22.04 -u agentforge -- bash -c "lsb_release -ds 2>/dev/null || (. /etc/os-release 2>/dev/null && echo $$PRETTY_NAME) || echo unknown"'
    Pop $R2
    Pop $R2
    nsExec::ExecToStack 'wsl.exe -d Ubuntu-22.04 -u agentforge -- bash -c "export NVM_DIR=$$HOME/.nvm; [ -s $$NVM_DIR/nvm.sh ] && . $$NVM_DIR/nvm.sh >/dev/null 2>&1; node -v 2>/dev/null || echo n/a"'
    Pop $R3
    Pop $R3

    FileOpen $9 "$LogBundle" "w"
    StrCmp $9 "" blb_done
    FileWrite $9 "===== AgentForge Setup Log =====$\r$\n"
    FileWrite $9 "Generated:     $LogStamp$\r$\n"
    FileWrite $9 "Installer:     AgentForge 2.1.0 (build ${BUILD_ID})$\r$\n"
    FileWrite $9 "Windows build: $R0$\r$\n"
    FileWrite $9 "WSL kernel:    $R1$\r$\n"
    FileWrite $9 "Distro:        $R2$\r$\n"
    FileWrite $9 "Node:          $R3$\r$\n"
    FileWrite $9 "ecc log:       inside Ubuntu at ~/.ecc/logs/install-$LogStamp.log$\r$\n"
    FileWrite $9 "(License keys, API keys, and other secrets are intentionally excluded from this log.)$\r$\n"
    FileWrite $9 "================================$\r$\n$\r$\n"
    FileClose $9

    Push "$LogBundle"
    Call DumpLog
    blb_done:
FunctionEnd

; ---------------------------------------------------------------
; License Key page (NEW) -- activation needs the key before install
; ---------------------------------------------------------------
Function LicensePageCreate
    !insertmacro MUI_HEADER_TEXT "Activate AgentForge" "Enter the license key from your purchase."

    nsDialogs::Create 1018
    Pop $0

    ${NSD_CreateLabel} 0 0 100% 32u "Paste the license key from your AgentForge purchase email. Your tier (Starter, Builder, or Pro) is detected automatically and its content is downloaded during install."
    Pop $0

    ${NSD_CreateLabel} 0 40u 100% 12u "License key:"
    Pop $0

    ${NSD_CreateText} 0 54u 100% 14u "$LicenseKey"
    Pop $LicenseHwnd

    ${NSD_CreateLabel} 0 76u 100% 32u "No key yet? Get one at https://agentforge.army/pricing -- or continue now and activate later in Ubuntu with:  ecc activate <your-license-key>"
    Pop $0

    nsDialogs::Show
FunctionEnd

Function LicensePageLeave
    ${NSD_GetText} $LicenseHwnd $LicenseKey

    ; Empty key -> documented escape hatch (install the CLI now, activate later).
    ${If} $LicenseKey == ""
        MessageBox MB_YESNO|MB_ICONQUESTION "No license key entered.$\r$\n$\r$\nAgentForge needs a license to download your tier's skills and agents. You can continue now and activate later in Ubuntu by running:$\r$\n$\r$\n  ecc activate <your-license-key>$\r$\n$\r$\nContinue without activating?" IDYES lic_skip
        Abort ; stay on the page
        lic_skip:
        StrCpy $SkipActivate "true"
        Return
    ${EndIf}

    StrLen $0 $LicenseKey
    ${If} $0 < 10
        MessageBox MB_OK|MB_ICONEXCLAMATION "That license key looks too short.$\r$\n$\r$\nPlease paste the full key from your purchase email."
        Abort ; stay on the page
    ${EndIf}

    ; --- LIVE pre-check ---------------------------------------------------------
    ; Validate the key NOW against LemonSqueezy /validate (non-activating, so it
    ; does not consume a device slot) so a wrong key is caught here in ~1s instead
    ; of after the multi-minute install. Runs pre-install, so we use Windows
    ; PowerShell (no WSL yet). Key passed via env (not the command line); TLS 1.2
    ; forced for Windows PowerShell 5.1. Output is VALID:<product> / INVALID / NETERR.
    StrCpy $SkipActivate "false"
    System::Call 'kernel32::SetEnvironmentVariable(t "AF_LICENSE", t "$LicenseKey")i.r0'
    nsExec::ExecToStack "powershell -NoProfile -ExecutionPolicy Bypass -Command $\"[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; try { $$r = Invoke-RestMethod -Method Post -Uri 'https://api.lemonsqueezy.com/v1/licenses/validate' -Body @{license_key=$$env:AF_LICENSE; instance_name='ecc-precheck'} -TimeoutSec 12; if ($$r.valid -eq $$true) { 'VALID:' + $$r.meta.product_name } else { 'INVALID' } } catch { $$c=0; try { $$c=[int]$$_.Exception.Response.StatusCode } catch {}; if ($$c -eq 400 -or $$c -eq 404 -or $$c -eq 422) { 'INVALID' } else { 'NETERR' } }$\""
    Pop $0 ; exit code
    Pop $1 ; output (VALID:<product> / INVALID / NETERR)
    System::Call 'kernel32::SetEnvironmentVariable(t "AF_LICENSE", i 0)i.r0'

    StrCpy $2 $1 6
    ${If} $2 == "VALID:"
        StrCpy $4 $1 "" 6 ; product name (trailing newline tolerated)
        MessageBox MB_OK|MB_ICONINFORMATION "License verified: $4$\r$\nClick Install to set up your environment and download your tier."
        Return
    ${EndIf}

    StrCpy $3 $1 7
    ${If} $3 == "INVALID"
        MessageBox MB_OK|MB_ICONSTOP "This license key isn't valid -- it may be mistyped, expired, or disabled.$\r$\n$\r$\nPlease re-check the key from your AgentForge purchase email and try again."
        Abort ; reject -- stay on the page
    ${EndIf}

    ; NETERR / unexpected -> could not verify (offline?). Let the buyer decide.
    MessageBox MB_YESNO|MB_ICONEXCLAMATION "Couldn't reach the license server to verify your key -- you may be offline.$\r$\n$\r$\nYou can continue (activation is retried during install), or fix your connection and click Next again.$\r$\n$\r$\nContinue anyway?" IDYES precheck_net_ok
    Abort ; stay on the page
    precheck_net_ok:
FunctionEnd

; ---------------------------------------------------------------
; Claude Sign-in page (BEFORE install) -- API key OR Claude subscription.
; This only captures the choice; the key (if any) is written to ~/.secrets during
; install, once Ubuntu exists. No WSL calls here -- WSL may not be set up yet.
; ---------------------------------------------------------------
Function ClaudeAuthPageCreate
    !insertmacro MUI_HEADER_TEXT "Connect to Claude" "Choose how Claude Code signs in -- you can change this later."

    nsDialogs::Create 1018
    Pop $0

    ${NSD_CreateLabel} 0 0 100% 24u "Claude Code -- the AI assistant at the heart of AgentForge -- needs to authenticate. Pick whichever you have. Most buyers use a Claude subscription."
    Pop $0

    ${NSD_CreateRadioButton} 0 30u 100% 11u "Use my Claude subscription (Claude Max or Pro)"
    Pop $ApiRadioSub
    ${NSD_CreateLabel} 5% 42u 90% 18u "Recommended if you pay for Claude. You'll sign in the first time you run  claude  -- nothing to paste now."
    Pop $0

    ${NSD_CreateRadioButton} 0 66u 100% 11u "Use an Anthropic API key (pay-as-you-go)"
    Pop $ApiRadioKey
    ${NSD_CreateLabel} 5% 78u 90% 10u "Get one at https://console.anthropic.com/settings/keys"
    Pop $0
    ${NSD_CreateText} 5% 90u 90% 14u ""
    Pop $ApiKeyHwnd
    SendMessage $ApiKeyHwnd ${EM_SETPASSWORDCHAR} 42 0

    ; Default: subscription selected, key field disabled.
    ${NSD_SetState} $ApiRadioSub ${BST_CHECKED}
    EnableWindow $ApiKeyHwnd 0
    ${NSD_OnClick} $ApiRadioSub OnPickSub
    ${NSD_OnClick} $ApiRadioKey OnPickKey

    ; Restore the API-key choice if the buyer came Back to this page.
    ${If} $ApiKeyText != ""
        ${NSD_SetText} $ApiKeyHwnd "$ApiKeyText"
        Call OnPickKey
    ${EndIf}

    nsDialogs::Show
FunctionEnd

; Mutually-exclusive selection enforced explicitly (robust regardless of WS_GROUP).
Function OnPickSub
    ${NSD_SetState} $ApiRadioSub ${BST_CHECKED}
    ${NSD_SetState} $ApiRadioKey ${BST_UNCHECKED}
    EnableWindow $ApiKeyHwnd 0
FunctionEnd

Function OnPickKey
    ${NSD_SetState} $ApiRadioKey ${BST_CHECKED}
    ${NSD_SetState} $ApiRadioSub ${BST_UNCHECKED}
    EnableWindow $ApiKeyHwnd 1
    ${NSD_SetFocus} $ApiKeyHwnd
FunctionEnd

Function ClaudeAuthPageLeave
    ${NSD_GetState} $ApiRadioKey $0
    ${If} $0 != ${BST_CHECKED}
        StrCpy $ApiKeyText ""   ; subscription path -- nothing to store
        Return
    ${EndIf}

    ${NSD_GetText} $ApiKeyHwnd $ApiKeyText
    ${If} $ApiKeyText == ""
        MessageBox MB_YESNO|MB_ICONQUESTION "You chose the API-key option but left the field empty.$\r$\n$\r$\nUse your Claude subscription instead (sign in on first run)?$\r$\n$\r$\nYes = use subscription    No = go back and paste a key" IDYES auth_use_sub
        Abort ; stay on the page so they can paste a key
        auth_use_sub:
        StrCpy $ApiKeyText ""
        Return
    ${EndIf}

    StrCpy $0 $ApiKeyText 7
    ${If} $0 != "sk-ant-"
        MessageBox MB_YESNO|MB_ICONQUESTION "This doesn't look like an Anthropic API key (they start with sk-ant-). Save it anyway?" IDYES auth_key_ok
        Abort ; stay on the page
        auth_key_ok:
    ${EndIf}
FunctionEnd

; ---------------------------------------------------------------
; Main install
; ---------------------------------------------------------------
Section "Install" SecInstall
    SetOutPath $INSTDIR
    SetAutoClose false

    DetailPrint "==============================================="
    DetailPrint "  AgentForge installer -- build ${BUILD_ID}"
    DetailPrint "==============================================="

    ; ===========================================================
    ; PHASE 1: Windows (WSL2 + Ubuntu)
    ; ===========================================================
    ${If} $SkipWSLSetup == "false"

        ; 1. WSL feature
        !insertmacro StepMsg "Enabling Windows Subsystem for Linux..."
        nsExec::ExecToLog 'dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart'
        Pop $ExitCode
        ${If} $ExitCode == 3010
            StrCpy $NeedsReboot "true"
        ${ElseIf} $ExitCode != 0
            !insertmacro FailWithLog "Could not enable WSL. Your IT policy may be blocking this."
        ${EndIf}

        ; 2. Virtual Machine Platform
        !insertmacro StepMsg "Enabling Virtual Machine Platform..."
        nsExec::ExecToLog 'dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart'
        Pop $ExitCode
        ${If} $ExitCode == 3010
            StrCpy $NeedsReboot "true"
        ${ElseIf} $ExitCode != 0
            !insertmacro FailWithLog "Could not enable Virtual Machine Platform. Your IT policy may be blocking this."
        ${EndIf}

        ; Reboot if needed
        ${If} $NeedsReboot == "true"
            DetailPrint "WSL2 features enabled. Reboot required."
            CreateDirectory "$APPDATA\AgentForge"
            FileOpen $0 "$APPDATA\AgentForge\agentforge-resume.flag" w
            FileWrite $0 "post-reboot"
            FileClose $0
            WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "AgentForgeResume" '"$EXEPATH"'
            MessageBox MB_YESNO|MB_ICONQUESTION "Windows needs to restart to finish enabling WSL2.$\r$\n$\r$\nSetup will resume automatically after reboot.$\r$\n$\r$\nRestart now?" IDYES do_reboot
            ; User declined the required reboot -- intentional exit, not a failure.
            StrCpy $FailHandled "1"
            Abort
            do_reboot:
            Reboot
        ${EndIf}

        ; 3. WSL2 default
        !insertmacro StepMsg "Setting WSL2 as default..."
        nsExec::ExecToLog 'wsl.exe --set-default-version 2'
        Pop $ExitCode

        ; 4. Ubuntu 22.04
        !insertmacro StepMsg "Installing Ubuntu 22.04 (this may take a few minutes)..."
        ; Use raw nsExec here -- agentforge user doesn't exist yet
        nsExec::ExecToStack 'wsl.exe -d Ubuntu-22.04 -- bash -c "echo ok"'
        Pop $ExitCode
        Pop $WslOutput
        ${If} $ExitCode != 0
            nsExec::ExecToLog 'wsl.exe --install -d Ubuntu-22.04 --no-launch'
            Pop $ExitCode
            ${If} $ExitCode != 0
                nsExec::ExecToLog 'wsl.exe --install -d Ubuntu-22.04'
                Pop $ExitCode
            ${EndIf}
        ${EndIf}
        DetailPrint "Ubuntu 22.04 ready"

        ; 5. User
        !insertmacro StepMsg "Creating user account..."
        !insertmacro WslExec "root" "id -u agentforge 2>/dev/null || (useradd -m -s /bin/bash -G sudo agentforge && passwd -l agentforge)"
        ; Passwordless sudo for agentforge
        !insertmacro WslExec "root" "echo 'agentforge ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/agentforge && chmod 440 /etc/sudoers.d/agentforge"
        ; Set agentforge as default WSL user so steps 7+ run under correct account
        !insertmacro WslExec "root" "printf '[user]\ndefault=agentforge\n' > /etc/wsl.conf"
        nsExec::ExecToLog 'wsl.exe --shutdown'
        Pop $ExitCode
        Sleep 3000
        DetailPrint "User 'agentforge' ready (set as default)"

    ${Else}
        StrCpy $StepNum 5
        DetailPrint "Resuming after reboot..."
    ${EndIf}

    ; ===========================================================
    ; PHASE 2: Linux setup (all from this Windows GUI)
    ; ===========================================================

    ; 6. System packages -- split into VISIBLE stages. With -qq, a multi-minute build-essential
    ; download is totally silent and looks frozen (b6 was cancelled here). Use -q so progress
    ; (and apt's "Waiting for cache lock" messages) stream live. Clear a stuck apt holder first.
    ; Straight-line bash only -- compound for/until/if + $() do NOT survive the wsl transport
    ; (b5 proved it: "syntax error near unexpected token"); verify renders via SetCompress off + strings -el.
    !insertmacro StepMsg "Installing Linux packages..."
    DetailPrint "Clearing any stale apt locks..."
    !insertmacro WslExec "root" "pkill -9 -x apt-get 2>/dev/null; pkill -9 -f unattended-upgrade 2>/dev/null; sleep 2; rm -f /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock 2>/dev/null; dpkg --configure -a 2>/dev/null; true"
    DetailPrint "Updating package lists (about a minute)..."
    !insertmacro WslMustPass "root" "apt-get update -q -o DPkg::Lock::Timeout=300" "Could not update package lists (check internet, or apt is locked -- see the lines above)."
    DetailPrint "Installing git, curl, jq, build-essential, python3-venv (a few minutes -- progress streams below, please wait)..."
    !insertmacro WslMustPass "root" "DEBIAN_FRONTEND=noninteractive apt-get install -y -q -o DPkg::Lock::Timeout=300 git curl jq build-essential python3-venv" "Could not install system packages."

    ; 7. nvm
    !insertmacro StepMsg "Installing Node Version Manager..."
    !insertmacro WslCheck "test -d ~/.nvm && echo yes || echo no"
    StrCmp $WslOutput "yes$\r$\n" nvm_done 0
        !insertmacro WslMustPass "" "curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | PROFILE=/dev/null bash" "Could not install nvm."
    nvm_done:
    ; Ensure nvm is sourced in interactive shells
    !insertmacro WslExec "" "grep -qF NVM_DIR $$HOME/.bashrc 2>/dev/null || printf '%s\n' '' '# nvm' 'export NVM_DIR=\$$HOME/.nvm' '[ -s \$$NVM_DIR/nvm.sh ] && . \$$NVM_DIR/nvm.sh' >> $$HOME/.bashrc"
    DetailPrint "nvm ready"

    ; 8. Node.js
    !insertmacro StepMsg "Installing Node.js 22 LTS..."
    ; Skip if node 22+ already available (via nvm or system)
    !insertmacro WslCheck "export NVM_DIR=$$HOME/.nvm; [ -s $$NVM_DIR/nvm.sh ] && . $$NVM_DIR/nvm.sh >/dev/null 2>&1; node --version 2>/dev/null | grep -qE 'v2[2-9]' && echo yes || echo no"
    StrCmp $WslOutput "yes$\r$\n" node_done 0
        ; Prefer nvm (user-level, no root) but try it QUIETLY: on many systems it is
        ; not usable non-interactively, and we don't want a scary error mid-install.
        ; If it doesn't take, fall through to the reliable apt path with neutral wording.
        DetailPrint "Setting up Node.js 22 LTS..."
        !insertmacro WslExec "" "export NVM_DIR=$$HOME/.nvm && [ -s $$NVM_DIR/nvm.sh ] && . $$NVM_DIR/nvm.sh >/dev/null 2>&1 && nvm install 22 >/dev/null 2>&1 && nvm alias default 22 >/dev/null 2>&1"
        ${If} $ExitCode != 0
            ; Reliable path: NodeSource apt repo. -q (not -qq) so progress streams live.
            DetailPrint "Installing Node.js 22 (about a minute -- progress streams below, please wait)..."
            !insertmacro WslMustPass "root" "curl -fsSL https://deb.nodesource.com/setup_22.x -o /tmp/nodesource.sh && bash /tmp/nodesource.sh && apt-get install -y -q -o DPkg::Lock::Timeout=300 nodejs && rm -f /tmp/nodesource.sh" "Could not install Node.js. Check your internet connection and re-run."
        ${EndIf}
    node_done:
    DetailPrint "Node.js ready"

    ; 9. Claude Code
    !insertmacro StepMsg "Installing Claude Code..."
    !insertmacro WslCheck "export NVM_DIR=$$HOME/.nvm; [ -s $$NVM_DIR/nvm.sh ] && . $$NVM_DIR/nvm.sh >/dev/null 2>&1; command -v claude >/dev/null 2>&1 && echo yes || echo no"
    StrCmp $WslOutput "yes$\r$\n" claude_done 0
        DetailPrint "Installing Claude Code..."
        ; Try a user-level npm install first, QUIETLY. With system Node (apt) this needs
        ; root, so a silent first attempt avoids dumping a harmless EACCES; the root
        ; install below is the one that streams visible progress.
        !insertmacro WslExec "" "export NVM_DIR=$$HOME/.nvm; [ -s $$NVM_DIR/nvm.sh ] && . $$NVM_DIR/nvm.sh >/dev/null 2>&1; npm install -g @anthropic-ai/claude-code >/dev/null 2>&1"
        ${If} $ExitCode != 0
            DetailPrint "Finishing Claude Code setup..."
            !insertmacro WslMustPass "root" "npm install -g @anthropic-ai/claude-code" "Could not install Claude Code."
        ${EndIf}
    claude_done:
    DetailPrint "Claude Code ready"

    ; 9b. Claude authentication. Key path -> store the key. Subscription path -> make
    ; sure NO Anthropic key is configured, so claude signs in with the subscription.
    ${If} $ApiKeyText != ""
        DetailPrint "Saving your Anthropic API key..."
        ; SECURITY: the key travels via the Windows env + WSLENV so the LOGGED command
        ; shows only "$AF_APIKEY" (the variable name), never the value. printf emits
        ; nothing to stdout, so the secret never reaches the Details view / log bundle.
        System::Call 'kernel32::SetEnvironmentVariable(t "AF_APIKEY", t "$ApiKeyText")i.r0'
        System::Call 'kernel32::SetEnvironmentVariable(t "WSLENV", t "AF_APIKEY")i.r0'
        !insertmacro WslExec "" "mkdir -p ~/.secrets && chmod 700 ~/.secrets && printf '%s\n' $$AF_APIKEY > ~/.secrets/anthropic_api_key && chmod 600 ~/.secrets/anthropic_api_key"
        ; The .bashrc export references the file, not the key -- safe to log.
        !insertmacro WslExec "" "grep -qF ANTHROPIC_API_KEY ~/.bashrc 2>/dev/null || printf '\n# AgentForge -- Anthropic API key\nexport ANTHROPIC_API_KEY=$$(cat ~/.secrets/anthropic_api_key 2>/dev/null)\n' >> ~/.bashrc"
        System::Call 'kernel32::SetEnvironmentVariable(t "AF_APIKEY", i 0)i.r0'
        ; Finish-button launcher: API-key path just runs claude. The key is exported
        ; from ~/.bashrc, which the -lic launch sources before the launcher execs.
        !insertmacro WslExec "" "printf '%s\n' '#!/usr/bin/env bash' 'exec claude' > ~/.agentforge-claude && chmod +x ~/.agentforge-claude"
        ; Command Deck launcher (API-key path): no key scrubbing needed.
        !insertmacro WslExec "" "printf '%s\n' '#!/usr/bin/env bash' 'command -v ecc >/dev/null 2>&1 && exec ecc cockpit || exec ~/AgentForge/ecc cockpit' > ~/.agentforge-cockpit && chmod +x ~/.agentforge-cockpit"
    ${Else}
        ; Subscription path: force a fresh sign-in by removing EVERY API credential that
        ; could shadow it. claude's sources, all cleared here: (1) the env key the
        ; installer manages (secrets file + export across .bashrc/.profile/.bash_profile);
        ; (2) claude's stored login ~/.claude/.credentials.json from any prior run; and
        ; (3) -- the one that actually bit a real buyer -- a "primaryApiKey" that claude
        ; itself persists INSIDE ~/.claude.json when it was ever run with an API key on
        ; that box. Confirmed live: with (1)+(2) clear but primaryApiKey present, claude
        ; still launched in API mode; after jq-deleting it, claude says "Please run
        ; /login" (the subscription sign-in). We delete primaryApiKey +
        ; customApiKeyResponses + oauthAccount -- the last so a prior account's stale
        ; "API Usage Billing / <org>" banner does not show before sign-in (the /login flow
        ; repopulates oauthAccount). The rest of .claude.json (projects, onboarding) is
        ; kept. Single-quoted jq filter, no double quotes -> transport-safe.
        DetailPrint "Configuring Claude for subscription sign-in..."
        !insertmacro WslExec "" "rm -f ~/.secrets/anthropic_api_key ~/.claude/.credentials.json; sed -i '/# AgentForge -- Anthropic API key/d;/export ANTHROPIC_API_KEY=/d' ~/.bashrc ~/.profile ~/.bash_profile 2>/dev/null; true"
        !insertmacro WslExec "" "command -v jq >/dev/null 2>&1 && test -f ~/.claude.json && jq 'del(.primaryApiKey, .customApiKeyResponses, .oauthAccount)' ~/.claude.json > ~/.claude.json.aftmp && mv ~/.claude.json.aftmp ~/.claude.json; true"
        ; Finish-button launcher: subscription path unsets ANTHROPIC_API_KEY before
        ; exec'ing claude, so any key from a source we cannot scrub on the Linux side
        ; (chiefly WSLENV propagation from the user's Windows env, re-injected on every
        ; wsl call) is neutralized for the launched session -> claude shows sign-in.
        !insertmacro WslExec "" "printf '%s\n' '#!/usr/bin/env bash' 'unset ANTHROPIC_API_KEY' 'exec claude' > ~/.agentforge-claude && chmod +x ~/.agentforge-claude"
        ; Command Deck launcher (subscription path): unset the key so `claude` run inside
        ; the Deck terminal signs in with the subscription (mirrors the claude launcher).
        !insertmacro WslExec "" "printf '%s\n' '#!/usr/bin/env bash' 'unset ANTHROPIC_API_KEY' 'command -v ecc >/dev/null 2>&1 && exec ecc cockpit || exec ~/AgentForge/ecc cockpit' > ~/.agentforge-cockpit && chmod +x ~/.agentforge-cockpit"
    ${EndIf}

    ; b20 (#3b): pre-seed Claude's first-run "onboarding complete" gate so a CLEAN-distro
    ; install does NOT re-ask the theme + login-method pickers after the buyer already picked
    ; their auth method in THIS installer (the "double-ask"). Root cause: on a fresh box
    ; ~/.claude.json does not exist, so the subscription-path jq above is a no-op and claude
    ; runs its full first-run onboarding. hasCompletedOnboarding:true is the gate (confirmed
    ; against a working ~/.claude.json). Runs for BOTH auth paths: API-key -> claude launches
    ; in API mode with no theme picker; subscription -> straight to /login (no creds present).
    ; Transport-safe: single quotes + \042 (octal ") keep the bash -c "..." wrapper quote-free.
    ; Line 1 seeds a clean box (works even without jq); line 2 merges into an existing file
    ; (dirty box) and is fail-open when jq is absent.
    DetailPrint "Finishing Claude first-run setup..."
    !insertmacro WslExec "" "test -f ~/.claude.json || printf '{\042hasCompletedOnboarding\042:true}\n' > ~/.claude.json"
    !insertmacro WslExec "" "command -v jq >/dev/null 2>&1 && test -f ~/.claude.json && jq '.hasCompletedOnboarding = true' ~/.claude.json > ~/.claude.json.aftmp && mv ~/.claude.json.aftmp ~/.claude.json; true"

    ; ALWAYS remove any leftover ~/AgentForge AS ROOT first, then clone fresh. A prior run can
    ; leave a dir the agentforge user cannot delete -- root ops here run with HOME=/home/agentforge,
    ; so root-owned files land in agentforge's home -- which made git clone refuse ("destination
    ; already exists") and an agentforge-level rm silently fail to clear it. Root rm clears any
    ; ownership; absolute path avoids the HOME ambiguity.
    !insertmacro StepMsg "Downloading AgentForge..."
    DetailPrint "Fetching a fresh copy of AgentForge..."
    !insertmacro WslExec "root" "rm -rf /home/agentforge/AgentForge"
    !insertmacro WslMustPass "" "GIT_TERMINAL_PROMPT=0 timeout 120 git clone --depth 1 https://github.com/reinraus135-cyber/agentforge-install.git ~/AgentForge" "Could not download AgentForge. Check your internet."
    DetailPrint "AgentForge ready"

    ; 11. Activate license -> downloads + installs the entitled tier's content
    !insertmacro StepMsg "Activating your license and installing your tier..."
    !insertmacro WslExec "" "chmod +x ~/AgentForge/ecc"
    !insertmacro WslCheck "test -f ~/.ecc/.install-complete && echo yes || echo no"
    StrCmp $WslOutput "yes$\r$\n" ecc_done 0
        ${If} $SkipActivate == "true"
            DetailPrint "No license key entered -- skipping activation."
            DetailPrint "Activate later in Ubuntu: ~/AgentForge/ecc activate <your-license-key>"
            Goto ecc_done
        ${EndIf}
        DetailPrint "Validating license and downloading your tier (this may take a minute)..."
        ; SECURITY: pass the key via the Windows env + WSLENV so it reaches bash
        ; from the environment. The LOGGED command shows only "$AF_LICENSE" (the
        ; variable name), never the key value. ecc never echoes the key itself.
        System::Call 'kernel32::SetEnvironmentVariable(t "AF_LICENSE", t "$LicenseKey")i.r0'
        System::Call 'kernel32::SetEnvironmentVariable(t "WSLENV", t "AF_LICENSE")i.r0'
        nsExec::ExecToLog 'wsl.exe -d Ubuntu-22.04 -u agentforge -- bash -c "mkdir -p $$HOME/.ecc/logs; export NVM_DIR=$$HOME/.nvm; [ -s $$NVM_DIR/nvm.sh ] && . $$NVM_DIR/nvm.sh >/dev/null 2>&1; ECC_LOG=$$HOME/.ecc/logs/install-$LogStamp.log bash ~/AgentForge/ecc activate $$AF_LICENSE"'
        Pop $ExitCode
        System::Call 'kernel32::SetEnvironmentVariable(t "AF_LICENSE", i 0)i.r0'
        ${If} $ExitCode == 0
            !insertmacro WslExec "" "mkdir -p ~/.ecc && date -Iseconds > ~/.ecc/.install-complete"
            DetailPrint "License activated -- your tier is installed."
            ; Read the activated tier so the Finish page can name it (Starter/Builder/Pro).
            !insertmacro WslCheck "cat ~/.ecc/license.json 2>/dev/null | jq -r '.sku // empty' 2>/dev/null || echo ''"
            ${If} $WslOutput == "pro$\r$\n"
                StrCpy $Tier "Pro"
            ${ElseIf} $WslOutput == "builder$\r$\n"
                StrCpy $Tier "Builder"
            ${ElseIf} $WslOutput == "starter$\r$\n"
                StrCpy $Tier "Starter"
            ${EndIf}
        ${Else}
            DetailPrint "Activation did not complete (exit $ExitCode)."
            ; Classify the failure from the ecc log so the dialog names the real reason.
            ; grep is straight-line bash (&&/||), transport-safe through the wsl call.
            !insertmacro WslCheck "grep -qiE 'activation limit|device activation|maximum number' ~/.ecc/logs/install-$LogStamp.log 2>/dev/null && echo Y || echo N"
            ${If} $WslOutput == "Y$\r$\n"
                MessageBox MB_OK|MB_ICONEXCLAMATION "Your environment is installed, but this license is already active on the maximum number of devices.$\r$\n$\r$\nDeactivate it on a machine you no longer use (or reply to your purchase email for help), then run in Ubuntu:$\r$\n  ecc activate <your-license-key>"
            ${Else}
                !insertmacro WslCheck "grep -qiE 'network error|could not reach|download failed|timed out|could not resolve' ~/.ecc/logs/install-$LogStamp.log 2>/dev/null && echo Y || echo N"
                ${If} $WslOutput == "Y$\r$\n"
                    MessageBox MB_OK|MB_ICONEXCLAMATION "Your environment is installed, but we couldn't reach the license server to download your tier -- this looks like a network problem.$\r$\n$\r$\nOnce you're back online, run in Ubuntu:$\r$\n  ecc activate <your-license-key>"
                ${Else}
                    MessageBox MB_OK|MB_ICONEXCLAMATION "Your environment is installed, but license activation did not complete.$\r$\n$\r$\nCommon causes:$\r$\n  - the key was mistyped$\r$\n  - the key is already active on the maximum number of devices$\r$\n  - no internet connection$\r$\n$\r$\nActivate anytime in Ubuntu with:$\r$\n  ecc activate <your-license-key>$\r$\n$\r$\nDetails are in the setup log on your Desktop."
                ${EndIf}
            ${EndIf}
        ${EndIf}
    ecc_done:
    DetailPrint "AgentForge environment ready"

    ; --- Gated auth-source diagnostic (build with -DAUTHDIAG) ---------------------
    ; Reports WHERE an Anthropic key could be coming from (variable NAMES / file
    ; paths only -- never a secret value) so a returned support log reveals why the
    ; subscription path might still see a key: env (incl. WSLENV propagation from
    ; Windows) / stored creds / ~/.claude.json / shell files. This wsl call inherits
    ; the installer's Windows env, so 'ENV: SET' here is the WSLENV smoking gun.
    ; Transport-safe: single quotes + &&/||/;/| only; no double quotes / $() / ${}.
!ifdef AUTHDIAG
    DetailPrint "[diag] inspecting Claude auth sources (no secrets logged)..."
    !insertmacro WslExec "" "echo '=== AUTH DIAG ==='; printenv ANTHROPIC_API_KEY >/dev/null 2>&1 && echo 'ENV: SET' || echo 'ENV: empty'; test -f ~/.claude/.credentials.json && echo 'CREDS: present' || echo 'CREDS: absent'; grep -qiE 'primaryapikey|sk-ant' ~/.claude.json 2>/dev/null && echo 'CLAUDEJSON: key present' || echo 'CLAUDEJSON: clean'; printf 'FILES WITH KEY: '; grep -liE ANTHROPIC_API_KEY ~/.bashrc ~/.profile ~/.bash_profile /etc/environment /etc/profile 2>/dev/null | tr '\n' ' '; echo; echo '=== END DIAG ==='"
!endif

    ; 12. PATH + doctor
    !insertmacro StepMsg "Running final checks..."
    ; NOTE: \$$HOME / \$$PATH are escaped so they are written LITERALLY into .bashrc
    ; (expanded at shell-source time), not expanded through the WslExec transport at
    ; install time. Unescaped $$HOME/$$PATH expand here and bake the full Windows PATH
    ; -- with unquoted "(x86)" -- into .bashrc, which then errors on every shell. Mirror
    ; the nvm line's \$$ escaping (see step 8 above).
    !insertmacro WslExec "" "grep -qF AgentForge ~/.bashrc 2>/dev/null || printf '\n# AgentForge\nexport PATH=\$$HOME/AgentForge:\$$PATH\n' >> ~/.bashrc"
    !insertmacro WslExec "" "export NVM_DIR=$$HOME/.nvm; [ -s $$NVM_DIR/nvm.sh ] && . $$NVM_DIR/nvm.sh >/dev/null 2>&1; ECC_LOG=$$HOME/.ecc/logs/install-$LogStamp.log bash ~/AgentForge/ecc doctor"

    ; 12b. Pre-warm the Command Deck (build the python venv + token while we are online) so
    ; the first launch from the Finish button / shortcut is instant. Fail-open: a Command
    ; Deck setup hiccup must NEVER fail the install. Only when a tier was activated (content present).
    ${If} $SkipActivate != "true"
        DetailPrint "Preparing the Command Deck (one-time setup)..."
        !insertmacro WslExec "" "~/AgentForge/ecc cockpit --setup || true"
        ; The Command Deck IS the product, so ALWAYS wire the live-monitoring hooks +
        ; status line (no opt-in question). Idempotent; settings.json is backed up
        ; first; undo later with `ecc cockpit --uninstall-hooks`.
        DetailPrint "Enabling Command Deck live monitoring..."
        !insertmacro WslExec "" "~/AgentForge/ecc cockpit --install-hooks --yes || true"
    ${EndIf}

    DetailPrint ""
    DetailPrint "========================================="
    DetailPrint "  Installation complete!"
    DetailPrint "========================================="

    ; Capture the full run to one Desktop file (everything above streamed to Details).
    Call BuildLogBundle

    ; Add/Remove Programs entry
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge" "DisplayName" "AgentForge"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge" "Publisher" "AgentForge"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge" "DisplayVersion" "2.1.0"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge" "UninstallString" '"$INSTDIR\uninstall.exe"'
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge" "NoModify" 1
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge" "NoRepair" 1
    WriteUninstaller "$INSTDIR\uninstall.exe"

    ; Start Menu + Desktop shortcuts for the Command Deck (brand icon extracted to $INSTDIR).
    ; Target wsl.exe directly so the launcher runs `ecc cockpit` (start backend detached +
    ; open browser) then the console closes; minimized so the brief window is unobtrusive.
    SetOutPath "$INSTDIR"
    File "${__FILEDIR__}/assets/AgentForge.ico"
    CreateDirectory "$SMPROGRAMS\AgentForge"
    CreateShortcut "$SMPROGRAMS\AgentForge\Command Deck.lnk" "$SYSDIR\wsl.exe" "-d Ubuntu-22.04 --cd ~ -- bash -lic ~/.agentforge-cockpit" "$INSTDIR\AgentForge.ico" 0 SW_SHOWMINIMIZED "" "Open the AgentForge Command Deck"
    CreateShortcut "$DESKTOP\Command Deck.lnk" "$SYSDIR\wsl.exe" "-d Ubuntu-22.04 --cd ~ -- bash -lic ~/.agentforge-cockpit" "$INSTDIR\AgentForge.ico" 0 SW_SHOWMINIMIZED "" "Open the AgentForge Command Deck"
    ; Second shortcut: a standard Claude CLI terminal in Ubuntu. ~/.agentforge-claude
    ; handles subscription-vs-API-key auth. Shown NORMALLY -- it is an interactive terminal.
    CreateShortcut "$SMPROGRAMS\AgentForge\Claude CLI.lnk" "$SYSDIR\wsl.exe" "-d Ubuntu-22.04 --cd ~ -- bash -lic ~/.agentforge-claude" "$INSTDIR\AgentForge.ico" 0 SW_SHOWNORMAL "" "Open a Claude CLI terminal (Ubuntu)"
    CreateShortcut "$DESKTOP\Claude CLI.lnk" "$SYSDIR\wsl.exe" "-d Ubuntu-22.04 --cd ~ -- bash -lic ~/.agentforge-claude" "$INSTDIR\AgentForge.ico" 0 SW_SHOWNORMAL "" "Open a Claude CLI terminal (Ubuntu)"

SectionEnd

Section "Uninstall"
    ; Offer to remove the actual product inside WSL (the Windows side below is
    ; just the registry entry + uninstaller stub). 'ecc uninstall' removes only
    ; ECC's footprint -- the buyer's own ~/.claude content and Claude login stay.
    MessageBox MB_YESNO|MB_ICONQUESTION "Remove the AgentForge environment inside Ubuntu (skills, agents, rules, license)?$\r$\n$\r$\nYour Claude config and sign-in are kept unless you also choose the full Ubuntu wipe in the next step.$\r$\n$\r$\nYes = remove AgentForge    No = remove only the Windows entry" IDNO uninst_win_only
    DetailPrint "Removing the AgentForge environment from Ubuntu..."
    nsExec::ExecToLog 'wsl.exe -d Ubuntu-22.04 -u agentforge -- bash -c "test -x $$HOME/AgentForge/ecc && $$HOME/AgentForge/ecc uninstall --yes; rm -rf $$HOME/AgentForge; true"'
    ; Optional full wipe: unregister the whole Ubuntu-22.04 distro. This destroys the
    ; ENTIRE Linux environment (Claude Code, the Claude sign-in, every file) -- not just
    ; AgentForge -- and cannot be undone. Clearly gated behind its own confirmation.
    MessageBox MB_YESNO|MB_ICONEXCLAMATION|MB_DEFBUTTON2 "Also COMPLETELY remove the Ubuntu-22.04 Linux environment?$\r$\n$\r$\nThis ERASES EVERYTHING inside it -- Claude Code, your Claude sign-in, and ALL your files in Ubuntu -- not just AgentForge. It cannot be undone.$\r$\n$\r$\nYes = erase all of Ubuntu    No = keep Ubuntu" IDNO uninst_keep_distro
    DetailPrint "Unregistering the Ubuntu-22.04 distro (full wipe)..."
    nsExec::ExecToLog 'wsl.exe --unregister Ubuntu-22.04'
    uninst_keep_distro:
    uninst_win_only:

    DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "AgentForgeResume"
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AgentForge"
    Delete "$APPDATA\AgentForge\agentforge-resume.flag"
    ; Command Deck + Claude CLI shortcuts + extracted brand icon
    Delete "$SMPROGRAMS\AgentForge\Command Deck.lnk"
    Delete "$SMPROGRAMS\AgentForge\Claude CLI.lnk"
    RMDir "$SMPROGRAMS\AgentForge"
    Delete "$DESKTOP\Command Deck.lnk"
    Delete "$DESKTOP\Claude CLI.lnk"
    Delete "$INSTDIR\AgentForge.ico"
    Delete "$INSTDIR\uninstall.exe"
    RMDir "$INSTDIR"
SectionEnd
